/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package jpro;

import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author DIGIT
 */
public class AllocateHostel extends javax.swing.JInternalFrame {

    /**
     * Creates new form AllocateHostel
     */
    Connection con;
    ResultSet r, r2;
    PreparedStatement s;

    public AllocateHostel() {
        initComponents();
        hostel.setVisible(false);
        room.setVisible(false);
        cost1.setVisible(false);
        cb1.setVisible(false);
        cb2.setVisible(false);
        addroom.setVisible(false);
    }

    public void addidtohosteltable() {
        String residence = cb1.getSelectedItem().toString();
        String room = cb2.getSelectedItem().toString();
        String sid = id.getText();
        String sname = name.getText();
        try {
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/data", "root", "");
            s = con.prepareStatement("update " + residence + " set student_id='" + sid + "', sname='" + sname + "', vacancy='no' where room='" + room + "'");
            s.executeUpdate();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error!");
        }
    }

    public void addroomtostudent() {
        String residence = cb1.getSelectedItem().toString();
        String room = cb2.getSelectedItem().toString();
        String sid = id.getText();
        try {
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/data", "root", "");
            s = con.prepareStatement("update student set residence='" + residence + "' , room='" + room + "' where id='" + sid + "'");
            s.executeUpdate();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error!");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        cb1 = new javax.swing.JComboBox();
        hostel = new javax.swing.JLabel();
        cb2 = new javax.swing.JComboBox();
        room = new javax.swing.JLabel();
        cost1 = new javax.swing.JLabel();
        cost = new javax.swing.JLabel();
        login = new javax.swing.JButton();
        addroom = new javax.swing.JButton();

        setClosable(true);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Allocation", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial Black", 0, 24), new java.awt.Color(255, 0, 102))); // NOI18N

        jLabel1.setText("UW ID");

        jLabel2.setText("Name");

        cb1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "uwp", "rev", "v1" }));
        cb1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb1ItemStateChanged(evt);
            }
        });
        cb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb1ActionPerformed(evt);
            }
        });

        hostel.setText("Residence");

        room.setText("Room");

        cost1.setText("Cost:");

        login.setText("Log In");
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });

        addroom.setText("Add Room");
        addroom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addroomActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(login)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(id, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                        .addComponent(name)))
                .addContainerGap(258, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 6, Short.MAX_VALUE)
                .addComponent(hostel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cb1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(room)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cb2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cost1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cost, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(addroom))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(login)
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cost, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cb1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(hostel)
                        .addComponent(cb2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(room)
                        .addComponent(cost1)))
                .addGap(18, 18, 18)
                .addComponent(addroom)
                .addContainerGap(73, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        // TODO add your handling code here:
        String sid = id.getText();
        String sname = name.getText();
        try {
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/data", "root", "");
            s = con.prepareStatement("select * from student where id='" + sid + "'");
            r = s.executeQuery();

            if (r.next() && sname.equals(r.getString("sname"))) {
                if (!r.getString("residence").equals("-")) {
                    JOptionPane.showMessageDialog(null, "Residence Already allocated !!");
                } else {
                    hostel.setVisible(true);
                    room.setVisible(true);
                    cb1.setVisible(true);
                    cb2.setVisible(true);
                    addroom.setVisible(true);
                }
            } else {
                JOptionPane.showMessageDialog(null, "Information Incorrect !!");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error!!");
        }

    }//GEN-LAST:event_loginActionPerformed

    private void cb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb1ActionPerformed
        // TODO add your handling code here:
        if (cb1.getSelectedItem().equals("uwp")) {
            cost1.setVisible(true);
            cost.setText("Rs 3000/Month");
            cb2.removeAllItems();
            try {
                con = DriverManager.getConnection("jdbc:mysql://localhost:3306/data", "root", "");
                s = con.prepareStatement("select * from uwp where vacancy='yes'");
                r2 = s.executeQuery();
                while (r2.next()) {
                    if (r2.getString("vacancy").equals("yes")) {
                        cb2.addItem(r2.getString("room"));
                    }
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Error!");
            }

        } else if (cb1.getSelectedItem().equals("rev")) {
            cost1.setVisible(true);
            cost.setText("Rs 5000/Month");
            cb2.removeAllItems();
            try {
                con = DriverManager.getConnection("jdbc:mysql://localhost:3306/data", "root", "");
                s = con.prepareStatement("select * from rev where vacancy='yes'");
                r2 = s.executeQuery();
                while (r2.next()) {
                    cb2.addItem(r2.getString("room"));
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Error!");
            }
        } else if (cb1.getSelectedItem().equals("v1")) {
            cost1.setVisible(true);
            cost.setText("Rs 8000/Month");
            cb2.removeAllItems();
            try {
                con = DriverManager.getConnection("jdbc:mysql://localhost:3306/data", "root", "");
                s = con.prepareStatement("select * from v1 where vacancy='yes'");
                r2 = s.executeQuery();
                while (r2.next()) {
                    cb2.addItem(r2.getString("room"));
                }   
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Error!");
            }

        }

    }//GEN-LAST:event_cb1ActionPerformed

    private void cb1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb1ItemStateChanged
        // TODO add your handling code here:

    }//GEN-LAST:event_cb1ItemStateChanged

    private void addroomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addroomActionPerformed
        // TODO add your handling code here:
        addidtohosteltable();
        addroomtostudent();
        hostel.setVisible(false);
        room.setVisible(false);
        cb1.setVisible(false);
        cb2.setVisible(false);
        addroom.setVisible(false);
        cost.setVisible(false);
        cost1.setVisible(false);
        JOptionPane.showMessageDialog(null, "Added Successfully!!");

    }//GEN-LAST:event_addroomActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addroom;
    private javax.swing.JComboBox cb1;
    private javax.swing.JComboBox cb2;
    private javax.swing.JLabel cost;
    private javax.swing.JLabel cost1;
    private javax.swing.JLabel hostel;
    private javax.swing.JTextField id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton login;
    private javax.swing.JTextField name;
    private javax.swing.JLabel room;
    // End of variables declaration//GEN-END:variables
}
